name: insect-wing-tracking
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - pillow
  - tqdm
  - pytorch
  - torchvision
  - opencv
  - imageio
  - imageio-ffmpeg
  - einops
  - easydict
  - huggingface_hub
  - decord
